### PR TITLE
Update package.json peerDependencies to support react 18.

### PR DESCRIPTION
**Pull request by mjauernig**
Update package.json peerDependencies to support react 18.

### CODE REVIEW

**Comment by thmsgbrt** [comment]
Hi @mjauernig 
Have you been testing this lib with React 18? Is there any issue with it?

**Comment by mjauernig** [comment]
Hi @thmsgbrt,

i had no problems. But i tested it not much with react 18. Only on one view.

**Comment by jatinhemnani01** [comment]
@mjauernig hey how can I install this without pull req accepting?

**Review by jatinhemnani01 — APPROVED** [review]

**Comment by mjauernig** [comment]
> @mjauernig hey how can I install this without pull req accepting?

Sorry. I d don't understand the questions. What do you mean with "install"?

**Review by thmsgbrt — APPROVED** [review]

**Comment by thmsgbrt** [comment]
Hi guys, @mjauernig, I've merged your PR and published 1.3.3 :)

**Pull request merged**
